_BASE_: "training.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 4
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0002
  STEPS: (4500, 7501)
  MAX_ITER: 7500
  WARMUP_ITERS: 300
  CHECKPOINT_PERIOD: 5000
INPUT:
  FS:
    FEW_SHOT: True
VERSION: 2
