_BASE_: pretraining.yaml
MODEL:
  META_ARCHITECTURE: FsodRCNN
  BACKBONE:
    FREEZE_AT: 3
  RPN:
    PRE_NMS_TOPK_TEST: 12000
    POST_NMS_TOPK_TEST: 100
    # PRE_NMS_TOPK_TRAIN: 12000
    # PRE_NMS_TOPK_TEST: 6000
    # POST_NMS_TOPK_TRAIN: 2000
    # POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: FsodStandardROIHeads
    BATCH_SIZE_PER_IMAGE: 128
    NUM_CLASSES: 1
    SCORE_THRESH_TEST: 0.0
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00002
  STEPS: (22500, 30000)
  MAX_ITER: 30001
  WARMUP_ITERS: 750
  WARMUP_FACTOR: 0.1
  CHECKPOINT_PERIOD: 10000
  HEAD_LR_FACTOR: 2.0
INPUT:
  FS:
    ENABLED: True
    SUPPORT_WAY: 2
    SUPPORT_SHOT: 30
VERSION: 2